import React from "react";
import "../style/affilate.css";

const Affilate = () => {
  return (
    <>
      <div className='partner-intro partner1'>
        <div className='banner inactive'>
          <div class='viewport'>
            {/* <img
              class='none'
              src='https://cdn.superbuy.com/starit-superbuy/dist/cn/source/img/about/affiliate/icon_en.png'
            /> */}
            <div class='inactive'>
              <div class='pic'>
                <img
                  class='banner_txt'
                  src='https://cdn.superbuy.com/starit-superbuy/dist/cn/source/img/about/affiliate/banner_txt1_en.png'
                  alt=''
                />
              </div>
              <div class='tip'>
                <p></p>
              </div>
            </div>
            <div class='btnJoin'>
              <div>
                <a href='' class='btn'>
                  Join
                </a>
              </div>
            </div>
            <div class='btnJoinNew'>
              <div>
                <a
                  href='http://bbs.superbuy.com/forum.php?mod=viewthread&amp;tid=228108&amp;fid=87'
                  class='btn'>
                  User Guide
                </a>
              </div>
            </div>
          </div>
        </div>
        <div className='wrap-bg'>
          <div class='intro-box'>
            <div class='viewport'>
              <div class='tit'>
                <h3>Superbuy Affiliates</h3>
                <div class='intro-txt'>
                  <p className='m-0'>Who are Superbuy Affiliates?</p>
                  <p className='m-0'>
                    Individuals and business customers who promote through the
                    Superbuy Affiliates marketing system.
                  </p>
                </div>
                <a class='rule' href=''>
                  Rules&gt;
                </a>
              </div>
              <div class='cont'>
                <div class='top-cont d-flex -align-items-center justify-content-between text-center'>
                  <div class='top-l-txt'>
                    <p className='m-0'>Register to Become a Superbuy Member</p>
                    <p className='m-0'>Join Affiliates Program</p>
                  </div>
                  <div class='top-r-txt'>
                    <p className='m-0'>New Users</p>
                    <p className='m-0'>Enjoy a ￥560 shipping coupon bundle</p>
                  </div>
                </div>
                <div class='center-cont-affiliate'>
                  <div className='center-cont-affiliate__text'>
                    <p class='center-t-txt text-start m-0'>
                      <em>Promote to affiliated users.</em>
                      <a href='//www.superbuy.com/en/page/partner'>
                        Promote Now
                      </a>
                    </p>
                    <p class='center-t-txt text-start m-0'>
                      Invite others to register and become Superbuy users. When
                      the purchase is completed and international shipping
                      orders are generated by the invited users, you will get
                      shipping bonus.
                    </p>
                  </div>

                  <div class='name name1 text-start'>
                    <p className='m-0'>Individual / Group Affiliate</p>
                    <p className='m-0'>
                      <a
                        href='//www.superbuy.com/en/page/help/#p61_64_helpId1020'
                        class='link'>
                        Their Differences
                      </a>
                    </p>
                  </div>
                  <div class='name name2 text-end'>Affiliated Users</div>
                </div>
                <div class='bottom-cont'>
                  <div class='bottom-l-txt'>
                    Redeemable monthly bonus without limit
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className='share-data'>
            <div className='viewport'>
              <div class='tit'>
                <h3>Statisitcs about Superbuy Affiliates</h3>
              </div>
              <div class='tip'>From March 2017 to March 2019 </div>
              <ul class='detail-data m-0 p-0 d-flex alifin-items-center'>
                <li>
                  <p>46,133</p>
                  <p>Total affiliated users </p>
                </li>
                <li></li>
                <li>
                  <p>18,450</p>
                  <p>The best performing affiliate </p>
                </li>
                <li></li>
                <li>
                  <p>
                    <span>CN￥</span>338,917
                  </p>
                  <p>The highest earner </p>
                </li>
              </ul>
              <div class='chart'></div>
              <ul className='promote p-0 m-0 d-flex'>
                <li class='text-en'>
                  <p>12191</p>
                  <p>Basic Affiliate</p>
                  <div style={{ backgroundPosition: "0px 0px" }}></div>
                </li>
                <li class='text-en'>
                  <p>1375</p>
                  <p>Bronze Affiliate</p>
                  <div style={{ backgroundPosition: "0px -143px" }}> </div>
                </li>
                <li class='text-en'>
                  <p>1038</p>
                  <p>Silver Affiliate</p>
                  <div style={{ backgroundPosition: "0px -286px" }}> </div>
                </li>
                <li class='text-en'>
                  <p>324</p>
                  <p>Gold Affiliate</p>
                  <div style={{ backgroundPosition: "0px -429px" }}></div>
                </li>
                <li class='text-en'>
                  <p>188</p>
                  <p>Platinum Affiliate</p>
                  <div style={{ backgroundPosition: "0px -572px" }}></div>
                </li>
                <li class='text-en'>
                  <p>50</p>
                  <p>Diamond Affiliate</p>
                  <div style={{ backgroundPosition: "0px -715px" }}></div>
                </li>
              </ul>
              <div class='tip'>Locations of Affiliates</div>
              <div class='map'></div>
            </div>
          </div>
          <div className='how-box'>
            <div className='viewport'>
              <div class='tit'>
                <h3>HOW TO BUILD MY ALLIANCE</h3>
              </div>
              <div class='tip'>3 Easy Ways to Invite New Users</div>
              <div className='cont'>
                <div class='item item1'>
                  <dl class='dl1'>
                    <dt>
                      <p>SHARE REGISTRATION CODE</p>
                    </dt>
                    <dd>
                      <div class='pic'></div>
                      <div class='name'>
                        <b>Share Registration Code</b>
                      </div>
                      <div class='txt'>
                        The invitees are linked to you when they fill in the
                        code in the registration process.
                      </div>
                    </dd>
                  </dl>
                </div>
                <div class='item item2'>
                  <dl class='dl1'>
                    <dt>
                      <p>SHARE QR CODE</p>
                    </dt>
                    <dd>
                      <div class='pic'></div>
                      <div class='name'>
                        <b>SHARE QR CODE</b>
                      </div>
                      <div class='txt'>
                        The invitees are linked to you when they scan the code
                        and register.
                      </div>
                    </dd>
                  </dl>
                </div>
                <div class='item item3'>
                  <dl class='dl1'>
                    <dt>
                      <p>SHARE LINKS TO SUPERBUY PAGES</p>
                    </dt>
                    <dd>
                      <div class='pic'></div>
                      <div class='name'>
                        <b>SHARE LINKS TO SUPERBUY PAGES</b>
                      </div>
                      <div class='txt'>
                        The invitees are linked to you when they register
                        through the link you share.
                      </div>
                    </dd>
                  </dl>
                </div>
              </div>
              <div className='share'>
                <dl>
                  <dt>Tips:</dt>
                  <dd>
                    <em>1</em>
                    You can share to friends, families, coworkers, and groups
                    via all public platforms.
                    <span class='share-ico'></span>
                  </dd>
                  <dd>
                    <em>2</em>Share through Superbuy registration page.Share the
                    website with your friends who are looking for a good
                    shopping agent.
                  </dd>
                  <dd style={{ textIndent: "36px" }}>
                    New users will get a ￥560 shipping coupon bundle after
                    registration
                  </dd>
                  <dd>
                    <em>3</em>
                    Share Editor's Pick to friends who love shopping and
                    fashion.-
                    <a href='#'>View/Share</a>
                  </dd>
                  <dd>
                    <em>4</em>
                    Share Superbuy promotion events to friends who may want the
                    special offers.
                  </dd>
                </dl>
              </div>
            </div>
          </div>
          <div className='make-money'>
            <div className='viewport'>
              <div class='tit'>
                <h3>HOW TO EARN MORE BONUS</h3>
                <div class='rule'>
                  Relax and earn money
                  <a class='rule-btn' href=' '>
                    Rules&gt;
                  </a>
                </div>
              </div>
              <div className='cont'>
                <div class='sub-tit'>MORE EXPERIENCE VALUE, MORE BONUS!</div>
                <div class='tip'>
                  Invite new Superbuy members， The more you invite, the more
                  money you make. No limits!Each time your invitees complete an
                  international shipment order, the amount of the order will
                  turn into your experience value. The actual bonus ratio an
                  affiliate enjoys is closely related to the shipment discounts
                  its linked user receives.
                </div>
                <table className='me-0 !important'>
                  <thead>
                    <tr>
                      <th>Affiliate level</th>
                      <td>Lv1</td>
                      <td>Lv2</td>
                      <td>Lv3</td>
                      <td>Lv4</td>
                      <td>Lv5</td>
                      <td>Lv6</td>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <th>Title</th>
                      <td>Basic Affiliate</td>
                      <td>Bronze Affiliate</td>
                      <td>Silver Affiliate</td>
                      <td>Gold Affiliate</td>
                      <td>Platinum Affiliate</td>
                      <td>Diamond Affiliate</td>
                    </tr>
                    <tr>
                      <th>Bonus Percentage</th>
                      <td>1%≤bonus ratio≤4%</td>
                      <td>1%≤bonus ratio≤6%</td>
                      <td>1%≤bonus ratio≤6.5%</td>
                      <td>1%≤bonus ratio≤7%</td>
                      <td>1%≤bonus ratio≤7.5%</td>
                      <td>1%≤bonus ratio≤7.5%</td>
                    </tr>
                    <tr>
                      <th>Experience Value</th>
                      <td>0-5999</td>
                      <td>6000-19999</td>
                      <td>20000-99999</td>
                      <td>100000-799999</td>
                      <td>800000-1000000</td>
                      <td>1000000</td>
                    </tr>
                  </tbody>
                </table>
                <div class='money-rec mt-4'>
                  <div
                    class='sub-tit'
                    style={{ color: "#333", fontSize: "16px" }}>
                    Bonus Record of First Superbuy Affiliate
                  </div>
                  <div class='pic'>
                    <div class='inner-wrap'>
                      <img
                        src='https://cdn.superbuy.com/starit-superbuy/dist/en/source/img/about/affiliate/money_rec.png'
                        alt=''
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className='service'>
            <div className='viewport'>
              <div className='tit'>
                <h3>SUPERBUY EXCLUSIVE SERVICE</h3>
              </div>
              <div className='cont'>
                <ul class='clearfix list1  p-0'>
                  <li>
                    <p>Zero Service Fee</p>
                    <p>Promise</p>
                  </li>
                  <li>
                    <p>Smart Consolidation</p>
                    <p>Shipment Fee 30% Off</p>
                  </li>
                  <li>
                    <p>Expert Product</p>
                    <p>Inspection</p>
                  </li>
                  <li>
                    <p>Coverage of</p>
                    <p>200+ Countries</p>
                  </li>
                </ul>
                <ul class='clearfix list2 p-0'>
                  <li>
                    <p>Compensation</p>
                    <p>Guarantee</p>
                  </li>
                  <li>
                    <p>One-stop Purchase of</p>
                    <p>Multiple E-comm Platforms</p>
                  </li>
                  <li>
                    <p>Free Participation to Our</p>
                    <p>Affiliate Alliance</p>
                  </li>
                  <li>
                    <p>More</p>
                    <p>Welcome aboard</p>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div class='join-box' style={{ position: "static" }}>
          <div class='viewport d-flex justify-content-around align-items-center'>
            <div class='txt'>Join Superbuy Affiliates Program</div>
            <div class='btn'>
              <a href='' style={{ textDecoration: "none" }}>
                JOIN NOW
              </a>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Affilate;
